networks:
  interview-net:
    external: true

services:
  # 前端应用（已包含nginx）
  interview-web:
    image: interview-web:latest
    container_name: interview-web
    ports:
      - "10077:8080"  # 映射到宿主机的10077端口
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - interview-net
